version: '3'

services:
  db:
    build: 
      context : .
      dockerfile: Dockerfile
    container_name: Database
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: a
    ports:
      - "5050:80"
    depends_on:
      - db
  
volumes:
  data:
